strategy:
  venue: gate
  symbol: IN_USDT
  size: 100
  spread_bps: 20.0
  reprice_bps: 3.0
  debounce_ms: 50 #this is the clock for the quoting system
  cancel_buffer_ms: 50 #this is the buffer for after we submit our last cancellation till the time we can send off a new quote
risk:
  max_order_notional: 40.0
  max_position_notional: 50.0
mode:
  dry_run: false #switch for live vs dry run
  log_fills: false
  debug_prints: true
logging:
  enabled: true
  path: logs/gate_activity.csv
  flush_interval_ms: 200
credentials:
  api_key_env: gateio_api_key
  api_secret_env: gateio_secret_key
